import { createContext, ReactNode, useContext, useState } from "react";

type Language = "en" | "vn";

const translations = {
  en: {
    home: "Home",
    menu: "Menu",
    reserveTable: "Reserve Table",
    heroHeadline: "Authentic Thai Soul in the Heart of Da Nang",
    heroSub:
      "From the streets of Bangkok to the shores of Da Nang. Experience authentic spices, fresh local seafood, and traditional Thai hospitality.",
    heroTitle: "Thai Culinary Specialties",
    viewMenu: "View Menu",
    aboutTitle: "The Balance of Four",
    aboutText:
      "At Mix Food, we honor the ancient Thai philosophy of balancing four essential flavors — Salt, Sweet, Spicy, and Sour. Every dish is a symphony of fresh herbs, aromatic spices, and locally sourced seafood, prepared by our chefs who trained in Bangkok's finest kitchens. Step into our warm, inviting space and let us transport you to Thailand.",
    bestSellers: "Our Best Sellers",
    bestSellersSub: "Taste the dishes our guests return for, again and again.",
    reviews: "What Our Guests Say",
    location: "Find Us",
    address:
      "K38/37 Nguyen Duy Hieu (K49 Nguyen Van Thoai), Son Tra District, Da Nang City, Vietnam",
    hours: "Opening Hours",
    hoursValue: "9:00  – 21:50 Daily",
    phone: "(+84) 905 473 728",
    copyright: "© 2026 Mix Food Da Nang. All rights reserved.",
    greenCurry: "Green Curry Chicken",
    greenCurryDesc: "Coconut milk, Thai basil, bamboo shoots, kaffir lime.",
    tomYum: "Tom Yum Goong",
    somTum: "Som Tum Salad",
    somTumDesc: "Green papaya, dried shrimp, peanuts, chili-lime dressing.",
    mangoRice: "Mango Sticky Rice",
    mangoRiceDesc: "Sweet coconut sticky rice, fresh mango, coconut cream.",
    heroTomYum: "Tom Yum Goong",
    heroTomYumDesc: "Our signature spicy & sour soup with tiger prawns.",
    // Reservation page
    reservePageTitle: "Reserve Your Table",
    reservePageSub:
      "Book your dining experience at Mix Food. We look forward to welcoming you.",
    fullName: "Full Name",
    fullNamePlaceholder: "Enter your full name",
    phoneNumber: "Phone Number",
    phonePlaceholder: "+84 xxx xxx xxx",
    email: "Email",
    emailPlaceholder: "your@email.com",
    dateTime: "Date & Time",
    datePlaceholder: "Select date",
    timePlaceholder: "Select time",
    numberOfGuests: "Number of Guests",
    guestsPlaceholder: "Select guests",
    specialRequests: "Special Requests / Notes",
    specialRequestsPlaceholder: "Any dietary requirements or special occasion?",
    reserveButton: "Reserve Table",
    openingHours: "Opening Hours",
    openingHoursValue: "Monday – Sunday: 10:00 – 21:50",
    policy: "Restaurant Policy",
    policy1: "Reservations must be made at least 30 minutes in advance",
    policy2:
      "Tables are held for a maximum of 10 minutes after reservation time",
    policy3:
      "Groups of 8 or more guests should contact the restaurant directly",
    policy4: "Cancellations must be made at least 1 hour in advance",
    contact: "Contact",
    contactPhone: "(+84) 905 473 728",
    contactEmail: "mixfood1708@gmail.com",
    contactNote: "Call us directly for quick consultation and reservations.",
    guest: "guest",
    guests: "guests",
    reservationSuccess: "Reservation submitted successfully!",
    reservationSuccessDesc: "We'll confirm your booking shortly.",
    // Validation errors
    validationError: "Validation Error",
    validationRequired: "Please fill in all required fields",
    // API errors
    apiError: "Something went wrong. Please try again.",
    apiNetworkError: "We could not reach the restaurant service. Please try again shortly.",
    // Booking page specific
    bookingAddress: "Address",
    bookingAddressValue: "K49 Nguyen Van Thoai, Hoa Thuan Tay, Hai Chau, Da Nang",
    bookingPhone: "Phone",
    bookingPhoneValue: "0905 473 728",
    bookingHours: "Opening Hours",
    bookingHoursValue: "09:00 - 21:50",
    guest1: "1 person",
    guest2: "2 people",
    guest3: "3 people",
    guest4: "4 people",
    guest5: "5 people",
    guest6: "6 people",
    guest7: "7 people",
    guest8: "8 people",
    guest9: "9 people",
    guest10: "10 people",
    guest10Plus: "More than 10 people",

    // Booking form specific
    bookingFormTitle: "Reservation Information",
    bookingFormDesc: "Please fill in all information below",
    bookingDate: "Reservation Date",
    bookingTime: "Time",
    bookingSelectDate: "Select date",
    bookingSelectTime: "Select time",
    bookingSelectGuests: "Select number of guests",
    bookingTimePlaceholder: "Select time",
    bookingTimeHelp: "Opening hours: 09:00 - 21:50. Please book at least 30 minutes in advance. Last booking is at 20:50.",
    bookingGuestsPlaceholder: "Enter number of guests",
    bookingSpecialRequests: "Special Requests (optional)",
    bookingSpecialRequestsPlaceholder: "E.g., Allergies, window seating, birthday cake...",
    bookingSpecialRequestsDesc: "We will try our best to accommodate your requests",
    bookingSubmitting: "Processing...",
    bookingSubmitButton: "Confirm Reservation",

    // Thai Dish Highlight Component
    thaiSpecialties: "Specialties of Thai Cuisine",
    thaiSpecialtiesDesc:
      "Discover authentic Thai dishes with distinctive flavors, prepared by professional chefs",
    orderNow: "Order Now",
    dishSpecialty: "Specialty Dish",
    whyChooseMixFood: "Why Choose Mix Food?",
    whyChooseMixFood1: "• Fresh ingredients imported from Thailand",
    whyChooseMixFood2: "• Professional chefs with 10+ years experience",
    whyChooseMixFood3: "• Authentic Thai flavors",
    whyChooseMixFood4: "• Elegant, modern space",
    dishImage: "Dish Image",
    dishImageCaption: "Photographed at Mix Food Da Nang",
    keywords: "Keywords",
    tomYumGoong: "Tom Yum Goong",
    tomYumVietnamese: "Spicy Lemongrass Soup with Prawns",
    tomYumDesc:
      "Signature Thai soup with spicy & sour flavor, fresh prawns, mushrooms and special herbs.",
    padThai: "Pad Thai",
    padThaiVietnamese: "Stir-Fried Thai Noodles",
    padThaiDesc:
      "Classic stir-fried noodles with shrimp, peanuts, bean sprouts and special sauce creating perfect balance.",
    somTam: "Som Tam",
    somTamVietnamese: "Green Papaya Salad",
    somTamDesc:
      "Green papaya salad mixed with tomatoes, peanuts, chili and fish sauce creating refreshing, flavorful Thai dish.",
    mangoStickyRice: "Mango Sticky Rice",
    mangoStickyRiceVietnamese: "Sweet Mango Rice",
    mangoStickyRiceDesc:
      "Sweet dessert with ripe mango combined with sticky coconut rice and fresh shredded coconut.",
    rating: "Rating",
    time: "Time",
    spicyLevel: "Spicy Level",
    minutes: "minutes",
    price: "Price",
    orderDishNow: "Order Dish Now",
    shareDish: "Share Dish",
    // Login page
    loginTitle: "Welcome Back",
    loginSubtitle: "Sign in to your account to continue",
    loginEmail: "Email",
    loginEmailPlaceholder: "Enter your email",
    loginEmailAddress: "Email Address",
    loginEmailPlaceholderAddress: "you@example.com",
    loginPassword: "Password",
    loginPasswordPlaceholder: "Enter your password",
    rememberMe: "Remember me",
    forgotPassword: "Forgot password?",
    forgotPasswordTitle: "Reset Your Password",
    forgotPasswordSubtitle: "Enter your email and we'll send you a password reset code",
    forgotPasswordButton: "Send Reset Code",
    forgotPasswordSending: "Sending...",
    forgotPasswordSuccessMessage: "Password reset code sent!",
    forgotPasswordSuccessDesc: "We've sent a reset code to",
    forgotPasswordCheckEmail: "Enter the code to choose a new password.",
    forgotPasswordBackToLogin: "Back to Login",
    fpOtpSubtitle: "Enter the 6-digit code sent to",
    fpOtpNote: "A 6-digit code was sent to your email. For security, it expires in 5 minutes.",
    fpOtpLabel: "Verification Code",
    fpVerifyButton: "Verify Code",
    fpVerifying: "Verifying...",
    fpNewPasswordTitle: "Set a New Password",
    fpNewPasswordSubtitle: "Enter and confirm your new password",
    fpNewPasswordLabel: "New Password",
    fpConfirmNewPasswordLabel: "Confirm New Password",
    fpResetButton: "Reset Password",
    fpResetting: "Resetting...",
    fpSuccessTitle: "Password Reset!",
    fpSuccessSubtitle: "You can now sign in with your new password",
    fpSuccessMessage: "Your password has been updated successfully. Please sign in again with your new password.",
    fpLoginNow: "Sign In Now",
    fpStepEmail: "Email",
    fpStepOtp: "Verify Code",
    fpStepNewPassword: "New Password",
    fpSendSuccess: "Reset code sent to your email",
    fpSendError: "We couldn't send the reset code. Please try again.",
    fpResendSuccess: "Reset code resent to your email",
    fpResendError: "We couldn't resend the code. Please try again.",
    fpOtpLengthError: "Please enter the 6-digit code",
    fpOtpVerifySuccess: "Code verified successfully",
    fpOtpVerifyError: "The verification code is invalid or has expired",
    fpResetSuccess: "Password reset successfully",
    fpResetError: "We couldn't reset your password. Please try again.",
    countdownResendIn: "Resend code in",
    countdownResend: "Resend Code",
    countdownSending: "Sending...",
    loginButton: "Sign In",
    loginSigningIn: "Signing in...",
    loginSuccess: "Login successful!",
    noAccount: "Don't have an account?",
    registerLink: "Sign up",
    // Register page
    registerTitle: "Create Account",
    registerSubtitle: "Join Mix Food and start your culinary journey",
    registerFullName: "Full Name",
    registerFullNamePlaceholder: "Enter your full name",
    registerEmail: "Email",
    registerEmailPlaceholder: "Enter your email",
    registerPassword: "Password",
    registerPasswordPlaceholder: "Create a password",
    registerConfirmPassword: "Confirm Password",
    registerConfirmPasswordPlaceholder: "Confirm your password",
    registerVerifyCode: "Verification Code",
    registerVerifyCodePlaceholder: "Enter 6-digit code",
    registerSendCode: "Send Code",
    registerResendCode: "Resend Code",
    registerResendIn: "Resend in {seconds}s",
    registerButton: "Create Account",
    registerHasAccount: "Already have an account?",
    registerLoginLink: "Sign in",
    registerCodeSent: "Verification code sent to your email",
    registerCodeError: "Failed to send verification code",
    registerPasswordMismatch: "Passwords do not match",
    registerPhoneNumber: "Phone Number",
    registerPhonePlaceholder: "0905 473 728",
    registerSending: "Sending...",
    registerCreating: "Creating account...",
    registerSuccess: "Registration successful!",
    registerStep1Label: "Account Info",
    registerStep2Label: "Verify Email",
    registerContinue: "Continue",
    registerBack: "Back",
    registerVerifySubtitle: "Enter the 6-digit verification code to confirm your email",
    registerEmailSentTo: "Verification code sent to",
    registerNoteSentToEmail: "The verification code was sent to your registered email. Please check your inbox (and your spam folder if you can't find it).",
    // Header
    headerSignIn: "Sign In",
    headerSignUp: "Sign Up",
    headerUser: "User",
    headerLogout: "Logout",
    // NotFound page
    notFoundTitle: "404",
    notFoundMessage: "Oops! Page not found",
    notFoundReturn: "Return to Home",
    // About component
    aboutSalt: "Salt",
    aboutSweet: "Sweet",
    aboutSpicy: "Spicy",
    aboutSour: "Sour",
    // Profile page
    profileTitle: "My Profile",
    profileUpdateInfo: "Update Info",
    profileChangePassword: "Change Password",
    profileCurrentPassword: "Current Password",
    profileCurrentPasswordPlaceholder: "Enter current password",
    profileNewPassword: "New Password",
    profileUpdateButton: "Save Changes",
    profileChangePasswordButton: "Change Password",
    profileUpdating: "Updating...",
    profileUpdateSuccess: "Profile updated successfully!",
    profilePasswordChanged: "Password changed successfully!",
    // Reservations page
    reservationsTitle: "Reservation History",
    reservationsSubtitle: "View and manage your table reservations",
    reservationsLoginRequired: "Login to view reservation history",
    reservationsLoginMessage: "You need to login to view your reservation history.",
    reservationsLoginButton: "Login now",
    reservationsEmpty: "No reservations yet",
    reservationsEmptyMessage: "You don't have any reservations yet. Book a table now to experience our service!",
    reservationsBookButton: "Book a table now",
    reservationsStatusPending: "Pending",
    reservationsStatusConfirmed: "Confirmed",
    reservationsStatusCancelled: "Cancelled",
    reservationsNote: "Note:",
    reservationsBookedAt: "Booked at:",
    reservationsDate: "Date:",
    reservationsTime: "Time:",
    reservationsGuests: "guests",
    reservationsTotal: "Total",
    reservationsTabAll: "All",
    reservationsSearch: "Search by name, phone...",
    reservationsSortNewest: "Newest",
    reservationsSortOldest: "Oldest",
    reservationsSortStatus: "By Status",
    reservationsRefresh: "Refresh",
    reservationsEmptyFiltered: "No reservations found",
    reservationsEmptyFilteredMessage: "No reservations match your filter criteria",
    reservationsCancel: "Cancel",
    reservationsRebook: "Rebook",
    reservationsViewDetails: "View Details",
    reservationsCopy: "Copy",
    reservationsPhone: "Phone",
    reservationsGuest: "guest",
    // Booking form messages
    bookingSuccess: "Reservation successful!",
    bookingSuccessDesc: "We'll contact you shortly to confirm.",
    bookingFailed: "Reservation failed",
    // Booking rules
    bookingRuleAdvance: "Advance Booking",
    bookingRuleAdvanceDesc: "Reservations must be made at least 30 minutes in advance",
    bookingRuleHold: "Table Hold Time",
    bookingRuleHoldDesc: "Tables are held for a maximum of 15 minutes after reservation time",
    bookingRuleCancel: "Cancellation Policy",
    bookingRuleCancelDesc: "Cancellations must be made at least 1 hour in advance",
    bookingRuleClosing: "Closing Time",
    bookingRuleClosingDesc: "Restaurant closes at 21:50. Bookings are accepted until 20:50",
    bookingRulesTitle: "Booking Rules",
    // Booking success page
    bookingSuccessTitle: "Reservation Confirmed!",
    bookingSuccessMessage: "Thank you for reserving at Mix Food. We'll contact you shortly to confirm your booking.",
    bookingReturnHome: "Back to Home",
    bookingViewMenu: "View Menu",
    bookingNeedHelp: "Need help?",
    bookingCallUs: "Call us at",
    // Profile extra
    profilePersonalInfoTitle: "Personal Information",
    profileChangePasswordTitle: "Change Password",
    profileAccountSettings: "Account Settings",
    profileMemberSince: "Member since",
    profileVerifiedAccount: "Verified Account",
    profileOrders: "Orders",
    profileRating: "Rating",
    profileConfirmNewPassword: "Confirm New Password",
    profileEmailNote: "Your email address cannot be changed.",
    // Menu extra
    menuTitle: "Our Menu",
    menuSubtitle: "Discover authentic Thai flavors crafted with the freshest ingredients",
    menuLoading: "Loading menu...",
    menuLoadError: "We couldn't load the menu. Please try again.",
    menuRetry: "Try again",
    menuNoDishes: "No dishes found",
    menuReadyToDine: "Ready to dine?",
    menuReadyToDineDesc: "Reserve your table now for an authentic Thai dining experience at Mix Food.",
    menuSearchPlaceholder: "Search dishes...",
    menuItems: "items",
    menuPrevious: "Previous",
    menuNext: "Next",
    tagPopular: "Popular",
    tagSpicy: "Spicy",
    tagVeggie: "Veggie",
    reservationsRefreshSuccess: "Booking list refreshed",
    reservationCancelComingSoon: "Table cancellation feature is coming soon",
    reservationCancelSuccess: "Reservation cancelled successfully",
    reservationCancelDialogTitle: "Cancel Reservation",
    reservationCancelDialogDescription: 'Are you sure you want to cancel the reservation for "{name}"? This action cannot be undone.',
    reservationCancelDialogKeep: "Keep reservation",
    reservationCancelDialogConfirm: "Yes, cancel",
    reservationCancelDialogConfirming: "Cancelling...",
    reservationsStatusArrived: "Arrived",
    reservationsCustomer: "Customer",
    reservationsStatus: "Status",
    reservationsActions: "Actions",
    reservationsCancelledBy: "Cancelled by",
    reservationsCancelledByUser: "You",
    reservationsCancelledByAdmin: "Restaurant",
    reservationsCancelledBySystem: "System",
    reservationsAutomaticCancellationReason: "Automatically cancelled because the guest did not arrive within 15 minutes.",
    reservationsCancellationReason: "Cancellation reason",
    reservationsCancellationReasonPlaceholder: "Tell us why you need to cancel",
    reservationsCancellationReasonHint: "This reason will be saved with your reservation.",
    reservationsUnknown: "Unknown",
    reservationsRefreshError: "Could not refresh reservation history",
    locale: "en-US",
    ariaMenuOpen: "Open menu",
    ariaMenuClose: "Close menu",
    // Footer
    footerAboutText: "Authentic Thai cuisine in Da Nang. Enjoy real Thai flavors with signature dishes served fresh.",
    footerQuickLinks: "Quick Links",
    footerContactUs: "Contact",
    footerAboutUs: "About Us",
    footerSpecialtyDishes: "Specialty Dishes",
    footerCopyright: "© {year} Mix Food. All rights reserved.",
    footerPrivacy: "Privacy Policy",
    footerTerms: "Terms of Service",
  },
  vn: {
    home: "Trang Chủ",
    menu: "Thực Đơn",
    reserveTable: "Đặt Bàn",
    heroHeadline: "Tinh Hoa Ẩm Thực Thái Giữa Lòng Đà Nẵng",
    heroSub:
      "Từ đường phố Bangkok đến bờ biển Đà Nẵng. Trải nghiệm gia vị đích thực, hải sản tươi sống và lòng hiếu khách truyền thống Thái Lan.",
    heroTitle: "Đặc Sắc Ẩm Thực Thái",
    viewMenu: "Xem Thực Đơn",
    aboutTitle: "Sự Cân Bằng Bốn Vị",
    aboutText:
      "Tại Mix Food, chúng tôi tôn vinh triết lý ẩm thực Thái cổ xưa về sự cân bằng bốn hương vị cơ bản — Mặn, Ngọt, Cay và Chua. Mỗi món ăn là một bản giao hưởng của thảo mộc tươi, gia vị thơm lừng và hải sản địa phương, được chế biến bởi các đầu bếp đào tạo tại những nhà hàng danh tiếng nhất Bangkok.",
    bestSellers: "Món Bán Chạy Nhất",
    bestSellersSub: "Thưởng thức những món ăn mà khách hàng luôn quay lại.",
    reviews: "Khách Hàng Nói Gì",
    location: "Tìm Chúng Tôi",
    address:
      "K38/37 Nguyen Duy Hieu (K49 Nguyen Van Thoai), Quận Sơn Trà, Thành phố Đà Nẵng, Việt Nam",
    hours: "Giờ Mở Cửa",
    hoursValue: "9:00 – 21:50 Hàng ngày",
    phone: "(+84) 905 473 728",
    copyright: "© 2026 Mix Food Đà Nẵng. Bảo lưu mọi quyền.",
    greenCurry: "Cà Ri Xanh Gà",
    greenCurryDesc: "Nước cốt dừa, húng quế Thái, măng, lá chanh kaffir.",
    tomYum: "Tom Yum Goong",
    somTum: "Gỏi Som Tum",
    somTumDesc: "Đu đủ xanh, tôm khô, đậu phộng, nước trộn chua cay.",
    mangoRice: "Xôi Xoài",
    mangoRiceDesc: "Xôi dừa ngọt, xoài tươi, kem dừa.",
    heroTomYum: "Tom Yum Goong",
    heroTomYumDesc: "Canh chua cay đặc trưng với tôm sú.",
    // Reservation page
    reservePageTitle: "Đặt Bàn",
    reservePageSub:
      "Đặt trải nghiệm ẩm thực tại Mix Food. Chúng tôi mong được chào đón bạn.",
    fullName: "Họ và Tên",
    fullNamePlaceholder: "Nhập họ và tên",
    phoneNumber: "Số Điện Thoại",
    phonePlaceholder: "+84 xxx xxx xxx",
    email: "Email",
    emailPlaceholder: "email@cuaban.com",
    dateTime: "Ngày & Giờ",
    datePlaceholder: "Chọn ngày",
    timePlaceholder: "Chọn giờ",
    numberOfGuests: "Số Lượng Khách",
    guestsPlaceholder: "Chọn số khách",
    specialRequests: "Yêu Cầu Đặc Biệt / Ghi Chú",
    specialRequestsPlaceholder: "Yêu cầu về chế độ ăn hoặc dịp đặc biệt?",
    reserveButton: "Đặt Bàn",
    openingHours: "Giờ Mở Cửa",
    openingHoursValue: "Thứ Hai – Chủ Nhật: 9:00 – 21:50",
    policy: "Chính Sách Nhà Hàng",
    policy1: "Đặt bàn phải được thực hiện ít nhất 30 phút trước",
    policy2: "Bàn được giữ tối đa 10 phút sau giờ đặt",
    policy3: "Nhóm từ 8 khách trở lên vui lòng liên hệ trực tiếp nhà hàng",
    policy4: "Hủy đặt bàn phải thực hiện ít nhất 1 giờ trước",
    contact: "Liên Hệ",
    contactPhone: "(+84) 905 473 728",
    contactEmail: "mixfood1708@gmail.com",
    contactNote: "Gọi trực tiếp để được tư vấn và đặt bàn nhanh chóng.",
    guest: "khách",
    guests: "khách",
    reservationSuccess: "Đặt bàn thành công!",
    reservationSuccessDesc: "Chúng tôi sẽ xác nhận đặt chỗ của bạn sớm.",
    // Validation errors
    validationError: "Lỗi Xác Thực",
    validationRequired: "Vui lòng điền đầy đủ các trường bắt buộc",
    // API errors
    apiError: "Đã có lỗi xảy ra. Vui lòng thử lại.",
    apiNetworkError: "Không thể kết nối đến nhà hàng. Vui lòng thử lại sau.",
    // Booking page specific
    bookingAddress: "Địa chỉ",
    bookingAddressValue: "K49 Nguyễn Văn Thoại, Hòa Thuận Tây, Hải Châu, Đà Nẵng",
    bookingPhone: "Số điện thoại",
    bookingPhoneValue: "0905 473 728",
    bookingHours: "Giờ mở cửa",
    bookingHoursValue: "09:00 - 21:50",
    guest1: "1 người",
    guest2: "2 người",
    guest3: "3 người",
    guest4: "4 người",
    guest5: "5 người",
    guest6: "6 người",
    guest7: "7 người",
    guest8: "8 người",
    guest9: "9 người",
    guest10: "10 người",
    guest10Plus: "Trên 10 người",

    // Booking form specific
    bookingFormTitle: "Thông Tin Đặt Bàn",
    bookingFormDesc: "Vui lòng điền đầy đủ thông tin bên dưới",
    bookingDate: "Ngày đặt bàn",
    bookingTime: "Giờ",
    bookingSelectDate: "Chọn ngày",
    bookingSelectTime: "Chọn giờ",
    bookingSelectGuests: "Chọn số lượng khách",
    bookingTimePlaceholder: "Chọn giờ",
    bookingTimeHelp: "Giờ mở cửa: 09:00 - 21:50. Vui lòng đặt bàn trước ít nhất 30 phút. Đặt bàn cuối cùng lúc 20:50.",
    bookingGuestsPlaceholder: "Nhập số lượng khách",
    bookingSpecialRequests: "Yêu cầu đặc biệt (tùy chọn)",
    bookingSpecialRequestsPlaceholder: "Ví dụ: Dị ứng, chỗ ngồi gần cửa sổ, bánh sinh nhật...",
    bookingSpecialRequestsDesc: "Chúng tôi sẽ cố gắng đáp ứng yêu cầu của bạn trong khả năng có thể",
    bookingSubmitting: "Đang xử lý...",
    bookingSubmitButton: "Xác Nhận Đặt Bàn",

    // Thai Dish Highlight Component
    thaiSpecialties: "Tinh hoa ẩm thực Thái",
    thaiSpecialtiesDesc:
      "Khám phá các món ăn Thái chính gốc với hương vị đặc trưng, được chế biến bởi đầu bếp chuyên nghiệp",
    orderNow: "Đặt ngay",
    dishSpecialty: "Món đặc trưng",
    whyChooseMixFood: "Vì sao chọn Mix Food?",
    whyChooseMixFood1: "• Nguyên liệu tươi nhập khẩu từ Thái Lan",
    whyChooseMixFood2: "• Đầu bếp chuyên nghiệp với hơn 10 năm kinh nghiệm",
    whyChooseMixFood3: "• Hương vị Thái chuẩn gốc",
    whyChooseMixFood4: "• Không gian hiện đại, sang trọng",
    dishImage: "Hình ảnh món ăn",
    dishImageCaption: "Chụp tại Mix Food Đà Nẵng",
    keywords: "Từ khóa",

    tomYumGoong: "Tom Yum Goong",
    tomYumVietnamese: "Canh chua cay tôm",
    tomYumDesc:
      "Món canh đặc trưng Thái Lan với vị chua cay, tôm tươi, nấm và các loại thảo mộc đặc biệt.",

    padThai: "Pad Thai",
    padThaiVietnamese: "Phở xào kiểu Thái",
    padThaiDesc:
      "Mì xào truyền thống với tôm, đậu phộng, giá đỗ và nước sốt đặc biệt tạo nên hương vị cân bằng hoàn hảo.",

    somTam: "Som Tam",
    somTamVietnamese: "Gỏi đu đủ",
    somTamDesc:
      "Gỏi đu đủ xanh trộn với cà chua, đậu phộng, ớt và nước mắm tạo nên món ăn tươi mát, đậm đà.",

    mangoStickyRice: "Xôi xoài",
    mangoStickyRiceVietnamese: "Xôi xoài ngọt",
    mangoStickyRiceDesc:
      "Món tráng miệng ngọt với xoài chín kết hợp cùng xôi dừa và dừa nạo tươi.",

    rating: "Đánh giá",
    time: "Thời gian",
    spicyLevel: "Độ cay",
    minutes: "phút",
    price: "Giá",
    orderDishNow: "Đặt món ngay",
    shareDish: "Chia sẻ món ăn",
    // Login page
    loginTitle: "Chào Mừng Trở Lại",
    loginSubtitle: "Đăng nhập vào tài khoản của bạn để tiếp tục",
    loginEmail: "Email",
    loginEmailPlaceholder: "Nhập email của bạn",
    loginEmailAddress: "Địa chỉ Email",
    loginEmailPlaceholderAddress: "ban@email.com",
    loginPassword: "Mật khẩu",
    loginPasswordPlaceholder: "Nhập mật khẩu của bạn",
    rememberMe: "Ghi nhớ đăng nhập",
    forgotPassword: "Quên mật khẩu?",
    forgotPasswordTitle: "Đặt Lại Mật Khẩu",
    forgotPasswordSubtitle: "Nhập email của bạn, chúng tôi sẽ gửi mã đặt lại mật khẩu",
    forgotPasswordButton: "Gửi mã đặt lại",
    forgotPasswordSending: "Đang gửi...",
    forgotPasswordSuccessMessage: "Đã gửi mã đặt lại mật khẩu!",
    forgotPasswordSuccessDesc: "Chúng tôi đã gửi mã đặt lại mật khẩu đến",
    forgotPasswordCheckEmail: "Nhập mã để chọn mật khẩu mới",
    forgotPasswordBackToLogin: "Quay lại đăng nhập",
    fpOtpSubtitle: "Nhập mã 6 chữ số đã gửi đến",
    fpOtpNote: "Mã 6 chữ số đã được gửi đến email của bạn. Vì lý do bảo mật, mã có hiệu lực trong 5 phút.",
    fpOtpLabel: "Mã xác thực",
    fpVerifyButton: "Xác nhận mã",
    fpVerifying: "Đang xác thực...",
    fpNewPasswordTitle: "Đặt Mật Khẩu Mới",
    fpNewPasswordSubtitle: "Nhập và xác nhận mật khẩu mới của bạn",
    fpNewPasswordLabel: "Mật khẩu mới",
    fpConfirmNewPasswordLabel: "Xác nhận mật khẩu mới",
    fpResetButton: "Đặt lại mật khẩu",
    fpResetting: "Đang xử lý...",
    fpSuccessTitle: "Đặt Lại Mật Khẩu Thành Công!",
    fpSuccessSubtitle: "Bạn có thể đăng nhập bằng mật khẩu mới",
    fpSuccessMessage: "Mật khẩu của bạn đã được cập nhật thành công. Vui lòng đăng nhập lại bằng mật khẩu mới.",
    fpLoginNow: "Đăng nhập ngay",
    fpStepEmail: "Email",
    fpStepOtp: "Xác thực mã",
    fpStepNewPassword: "Mật khẩu mới",
    fpSendSuccess: "Đã gửi mã đặt lại mật khẩu đến email của bạn",
    fpSendError: "Không thể gửi mã đặt lại mật khẩu. Vui lòng thử lại.",
    fpResendSuccess: "Đã gửi lại mã đặt lại mật khẩu đến email của bạn",
    fpResendError: "Không thể gửi lại mã. Vui lòng thử lại.",
    fpOtpLengthError: "Vui lòng nhập mã 6 chữ số",
    fpOtpVerifySuccess: "Xác thực mã thành công",
    fpOtpVerifyError: "Mã xác thực không hợp lệ hoặc đã hết hạn",
    fpResetSuccess: "Đặt lại mật khẩu thành công",
    fpResetError: "Không thể đặt lại mật khẩu. Vui lòng thử lại.",
    countdownResendIn: "Gửi lại mã sau",
    countdownResend: "Gửi lại mã",
    countdownSending: "Đang gửi...",
    loginButton: "Đăng Nhập",
    loginSigningIn: "Đang đăng nhập...",
    loginSuccess: "Đăng nhập thành công!",
    noAccount: "Chưa có tài khoản?",
    registerLink: "Đăng ký",
    // Register page
    registerTitle: "Tạo Tài Khoản",
    registerSubtitle: "Tham gia Mix Food và bắt đầu hành trình ẩm thực của bạn",
    registerFullName: "Họ và Tên",
    registerFullNamePlaceholder: "Nhập họ và tên của bạn",
    registerEmail: "Email",
    registerEmailPlaceholder: "Nhập email của bạn",
    registerPassword: "Mật khẩu",
    registerPasswordPlaceholder: "Tạo mật khẩu",
    registerConfirmPassword: "Xác Nhận Mật Khẩu",
    registerConfirmPasswordPlaceholder: "Xác nhận mật khẩu của bạn",
    registerVerifyCode: "Mã Xác Thực",
    registerVerifyCodePlaceholder: "Nhập mã 6 chữ số",
    registerSendCode: "Gửi Mã",
    registerResendCode: "Gửi Lại",
    registerResendIn: "Gửi lại sau {seconds}s",
    registerButton: "Tạo Tài Khoản",
    registerHasAccount: "Đã có tài khoản?",
    registerLoginLink: "Đăng nhập",
    registerCodeSent: "Mã xác thực đã được gửi đến email của bạn",
    registerCodeError: "Không thể gửi mã xác thực",
    registerPasswordMismatch: "Mật khẩu không khớp",
    registerPhoneNumber: "Số Điện Thoại",
    registerPhonePlaceholder: "0905 473 728",
    registerSending: "Đang gửi...",
    registerCreating: "Đang tạo tài khoản...",
    registerSuccess: "Đăng ký thành công!",
    registerStep1Label: "Thông tin tài khoản",
    registerStep2Label: "Xác thực email",
    registerContinue: "Tiếp tục",
    registerBack: "Quay lại",
    registerVerifySubtitle: "Nhập mã xác thực 6 chữ số để xác nhận email của bạn",
    registerEmailSentTo: "Mã xác thực đã được gửi đến",
    registerNoteSentToEmail: "Mã xác thực đã được gửi đến email đăng ký của bạn. Vui lòng kiểm tra hộp thư đến (và cả mục thư rác nếu bạn không thấy).",
    // Header
    headerSignIn: "Đăng Nhập",
    headerSignUp: "Đăng Ký",
    headerUser: "Người dùng",
    headerLogout: "Đăng xuất",
    // NotFound page
    notFoundTitle: "404",
    notFoundMessage: "Rất tiếc! Không tìm thấy trang",
    notFoundReturn: "Về Trang Chủ",
    // About component
    aboutSalt: "Mặn",
    aboutSweet: "Ngọt",
    aboutSpicy: "Cay",
    aboutSour: "Chua",
    // Profile page
    profileTitle: "Hồ Sơ Của Tôi",
    profileUpdateInfo: "Cập Nhật Thông Tin",
    profileChangePassword: "Đổi Mật Khẩu",
    profileCurrentPassword: "Mật Khẩu Hiện Tại",
    profileCurrentPasswordPlaceholder: "Nhập mật khẩu hiện tại",
    profileNewPassword: "Mật Khẩu Mới",
    profileUpdateButton: "Lưu Thay Đổi",
    profileChangePasswordButton: "Đổi Mật Khẩu",
    profileUpdating: "Đang cập nhật...",
    profileUpdateSuccess: "Cập nhật hồ sơ thành công!",
    profilePasswordChanged: "Đổi mật khẩu thành công!",
    // Reservations page
    reservationsTitle: "Lịch Sử Đặt Bàn",
    reservationsSubtitle: "Xem và quản lý các đặt bàn của bạn",
    reservationsLoginRequired: "Đăng nhập để xem lịch sử đặt bàn",
    reservationsLoginMessage: "Bạn cần đăng nhập để xem lịch sử đặt bàn của mình.",
    reservationsLoginButton: "Đăng nhập ngay",
    reservationsEmpty: "Chưa có đặt bàn nào",
    reservationsEmptyMessage: "Bạn chưa có đặt bàn nào. Hãy đặt bàn ngay để trải nghiệm dịch vụ của chúng tôi!",
    reservationsBookButton: "Đặt bàn ngay",
    reservationsStatusPending: "Chờ xác nhận",
    reservationsStatusConfirmed: "Đã xác nhận",
    reservationsStatusCancelled: "Đã hủy",
    reservationsNote: "Ghi chú:",
    reservationsBookedAt: "Đặt lúc:",
    reservationsDate: "Ngày:",
    reservationsTime: "Giờ:",
    reservationsGuests: "khách",
    reservationsTotal: "Tổng",
    reservationsTabAll: "Tất cả",
    reservationsSearch: "Tìm kiếm theo tên, số điện thoại...",
    reservationsSortNewest: "Mới nhất",
    reservationsSortOldest: "Cũ nhất",
    reservationsSortStatus: "Theo trạng thái",
    reservationsRefresh: "Làm mới",
    reservationsEmptyFiltered: "Không có đặt bàn nào",
    reservationsEmptyFilteredMessage: "Không tìm thấy đặt bàn nào phù hợp với bộ lọc",
    reservationsCancel: "Hủy",
    reservationsRebook: "Đặt lại",
    reservationsViewDetails: "Xem chi tiết",
    reservationsCopy: "Sao chép",
    reservationsPhone: "Điện thoại",
    reservationsGuest: "khách",
    // Booking form
    bookingSuccess: "Đặt bàn thành công!",
    bookingSuccessDesc: "Chúng tôi sẽ liên hệ với bạn sớm nhất để xác nhận.",
    bookingFailed: "Đặt bàn thất bại",
    // Booking rules
    bookingRuleAdvance: "Đặt bàn trước",
    bookingRuleAdvanceDesc: "Đặt bàn phải được thực hiện ít nhất 30 phút trước",
    bookingRuleHold: "Thời gian giữ bàn",
    bookingRuleHoldDesc: "Bàn được giữ tối đa 15 phút sau giờ đặt",
    bookingRuleCancel: "Chính sách hủy",
    bookingRuleCancelDesc: "Hủy đặt bàn phải thực hiện ít nhất 1 tiếng trước",
    bookingRuleClosing: "Giờ đóng cửa",
    bookingRuleClosingDesc: "Nhà hàng đóng cửa lúc 21:50. Nhận đặt bàn đến 20:50",
    bookingRulesTitle: "Quy định đặt bàn",
    // Booking success page
    bookingSuccessTitle: "Đặt Bàn Thành Công!",
    bookingSuccessMessage: "Cảm ơn bạn đã đặt bàn tại Mix Food. Chúng tôi sẽ liên hệ với bạn sớm nhất để xác nhận.",
    bookingReturnHome: "Về Trang Chủ",
    bookingViewMenu: "Xem Menu",
    bookingNeedHelp: "Cần hỗ trợ?",
    bookingCallUs: "Gọi cho chúng tôi tại",
    // Profile extra
    profilePersonalInfoTitle: "Thông Tin Cá Nhân",
    profileChangePasswordTitle: "Đổi Mật Khẩu",
    profileAccountSettings: "Cài Đặt Tài Khoản",
    profileMemberSince: "Thành viên từ",
    profileVerifiedAccount: "Tài Khoản Đã Xác Minh",
    profileOrders: "Đơn Hàng",
    profileRating: "Đánh Giá",
    profileConfirmNewPassword: "Xác nhận mật khẩu mới",
    profileEmailNote: "Địa chỉ email của bạn không thể thay đổi.",
    // Menu extra
    menuTitle: "Thực Đơn",
    menuSubtitle: "Khám phá hương vị Thái Lan đích thực với nguyên liệu tươi ngon nhất",
    menuLoading: "Đang tải thực đơn...",
    menuLoadError: "Không thể tải thực đơn. Vui lòng thử lại.",
    menuRetry: "Thử lại",
    menuNoDishes: "Không tìm thấy món ăn nào",
    menuReadyToDine: "Sẵn sàng thưởng thức?",
    menuReadyToDineDesc: "Đặt bàn ngay để trải nghiệm ẩm thực Thái Lan đích thực tại Mix Food.",
    menuSearchPlaceholder: "Tìm kiếm món ăn...",
    menuItems: "món",
    menuPrevious: "Trước",
    menuNext: "Tiếp",
    tagPopular: "Phổ biến",
    tagSpicy: "Cay",
    tagVeggie: "Chay",
    reservationsRefreshSuccess: "Đã làm mới danh sách đặt bàn",
    reservationCancelComingSoon: "Tính năng hủy đặt bàn đang được phát triển",
    reservationCancelSuccess: "Đã hủy đặt bàn thành công",
    reservationCancelDialogTitle: "Hủy đặt bàn",
    reservationCancelDialogDescription: 'Bạn có chắc muốn hủy đặt bàn của "{name}"? Hành động này không thể hoàn tác.',
    reservationCancelDialogKeep: "Giữ đặt bàn",
    reservationCancelDialogConfirm: "Có, hủy",
    reservationCancelDialogConfirming: "Đang hủy...",
    reservationsStatusArrived: "Đã đến",
    reservationsCustomer: "Khách hàng",
    reservationsStatus: "Trạng thái",
    reservationsActions: "Thao tác",
    reservationsCancelledBy: "Người hủy",
    reservationsCancelledByUser: "Bạn",
    reservationsCancelledByAdmin: "Nhà hàng",
    reservationsCancelledBySystem: "Hệ thống",
    reservationsAutomaticCancellationReason: "Tự động hủy vì khách không đến trong vòng 15 phút.",
    reservationsCancellationReason: "Lý do hủy",
    reservationsCancellationReasonPlaceholder: "Cho chúng tôi biết lý do bạn muốn hủy",
    reservationsCancellationReasonHint: "Lý do này sẽ được lưu cùng thông tin đặt bàn của bạn.",
    reservationsUnknown: "Không rõ",
    reservationsRefreshError: "Không thể làm mới lịch sử đặt bàn",
    locale: "vi-VN",
    ariaMenuOpen: "Mở menu",
    ariaMenuClose: "Đóng menu",
    // Footer
    footerAboutText: "Ẩm thực Thái chính thống tại Đà Nẵng. Thưởng thức hương vị đích thực từ Thái Lan với các món ăn đặc sắc.",
    footerQuickLinks: "Liên kết nhanh",
    footerContactUs: "Liên hệ",
    footerAboutUs: "Về chúng tôi",
    footerSpecialtyDishes: "Món ăn đặc sắc",
    footerCopyright: "© {year} Mix Food. Bảo lưu mọi quyền.",
    footerPrivacy: "Chính sách bảo mật",
    footerTerms: "Điều khoản sử dụng",
  },
};

const LanguageContext = createContext<{
  lang: Language;
  setLang: (l: Language) => void;
  t: (typeof translations)["en"];
}>({
  lang: "en",
  setLang: () => {},
  t: translations.en,
});

export const useLanguage = () => useContext(LanguageContext);

const getCookie = (name: string): string | null => {
  const match = document.cookie.match(new RegExp(`(^| )${name}=([^;]+)`));
  return match ? match[2] : null;
};

const setCookie = (name: string, value: string, days = 365) => {
  const expires = new Date(Date.now() + days * 864e5).toUTCString();
  document.cookie = `${name}=${value};expires=${expires};path=/;SameSite=Lax`;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Language>(() => {
    const saved = getCookie("lang");
    return saved === "vn" ? "vn" : "en";
  });

  const setLang = (l: Language) => {
    setLangState(l);
    setCookie("lang", l);
  };

  const t = translations[lang];
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
